"""
BillingTransaction model for tracking payment transactions.
Linked to UpgradeRequest for subscription upgrades.
"""
from sqlalchemy import Column, String, Integer, Boolean, Text, ForeignKey, DateTime, JSON
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from datetime import datetime, timezone
import uuid

from app.core.database import Base
from app.models.base import TenantScopedModel


class TransactionStatus:
    """Transaction status constants"""
    PENDING = "pending"
    PAID = "paid"
    CANCELLED = "cancelled"
    REFUNDED = "refunded"


class TransactionType:
    """Transaction type constants"""
    SUBSCRIPTION = "subscription"
    UPGRADE = "upgrade"
    DOWNGRADE = "downgrade"
    RENEWAL = "renewal"
    CREDIT = "credit"
    CREDIT_ADJUSTMENT = "credit_adjustment"  # Manual credit changes
    EXTENSION = "extension"  # Bonus days / duration extension
    PROMO = "promo"  # Promotional discount
    REFUND = "refund"  # Partial/full refunds
    MANUAL = "manual"  # Other manual adjustments


class BillingTransaction(Base, TenantScopedModel):
    """
    Billing transaction record for payment tracking.

    Each upgrade request creates one billing transaction.
    This provides invoice/receipt functionality.
    """
    __tablename__ = "billing_transactions"

    # Transaction identification
    transaction_number = Column(
        String(50),
        unique=True,
        nullable=False,
        index=True,
        comment="Unique transaction/invoice number"
    )

    # Link to upgrade request (optional - allows standalone transactions)
    upgrade_request_id = Column(
        UUID(as_uuid=True),
        ForeignKey("upgrade_requests.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
        comment="Associated upgrade request (optional for manual transactions)"
    )

    # Transaction type
    transaction_type = Column(
        String(30),
        nullable=False,
        default=TransactionType.SUBSCRIPTION,
        comment="Transaction type: subscription, upgrade, downgrade, renewal, credit"
    )

    # Transaction details (snapshot from upgrade request)
    amount = Column(
        Integer,
        nullable=False,
        comment="Final transaction amount (after credits)"
    )
    original_amount = Column(
        Integer,
        nullable=False,
        default=0,
        comment="Amount before credits applied"
    )
    credit_applied = Column(
        Integer,
        nullable=False,
        default=0,
        comment="Credits used in this transaction"
    )
    credit_generated = Column(
        Integer,
        nullable=False,
        default=0,
        comment="Credits generated by this transaction (for downgrades)"
    )
    currency = Column(
        String(3),
        nullable=False,
        default="IDR",
        comment="Currency code"
    )
    billing_period = Column(
        String(20),
        nullable=False,
        comment="monthly or yearly"
    )

    # Proration details
    proration_details = Column(
        sa.JSON(),
        nullable=True,
        comment="JSON with proration calculation breakdown"
    )

    # Billing period dates
    period_start = Column(
        DateTime(timezone=True),
        nullable=True,
        comment="Billing period start date"
    )
    period_end = Column(
        DateTime(timezone=True),
        nullable=True,
        comment="Billing period end date"
    )

    # Payment method reference
    payment_method_id = Column(
        UUID(as_uuid=True),
        ForeignKey("payment_methods.id", ondelete="SET NULL"),
        nullable=True,
        comment="Payment method used"
    )

    # Status tracking
    status = Column(
        String(50),
        nullable=False,
        default=TransactionStatus.PENDING,
        index=True,
        comment="Transaction status"
    )

    # Dates
    invoice_date = Column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        comment="Invoice generation date"
    )
    paid_at = Column(
        DateTime(timezone=True),
        nullable=True,
        comment="Payment confirmation date"
    )
    cancelled_at = Column(
        DateTime(timezone=True),
        nullable=True,
        comment="Cancellation date"
    )

    # Additional info
    notes = Column(
        Text,
        nullable=True,
        comment="Internal notes"
    )

    # Description for invoice
    description = Column(
        Text,
        nullable=True,
        comment="Line item description"
    )

    # Coupon/discount fields (for admin-applied discounts)
    coupon_id = Column(
        UUID(as_uuid=True),
        ForeignKey("coupons.id", ondelete="SET NULL"),
        nullable=True,
        comment="Applied coupon ID"
    )
    coupon_code = Column(
        String(50),
        nullable=True,
        comment="Applied coupon code (snapshot)"
    )
    discount_amount = Column(
        Integer,
        nullable=False,
        default=0,
        comment="Discount amount applied"
    )
    discount_description = Column(
        String(255),
        nullable=True,
        comment="Description of discount applied"
    )

    # Bonus/extension fields
    bonus_days = Column(
        Integer,
        nullable=False,
        default=0,
        comment="Bonus days added to subscription"
    )

    # Admin management fields
    admin_notes = Column(
        Text,
        nullable=True,
        comment="Internal admin notes"
    )
    adjusted_by_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        comment="Admin who made adjustments"
    )
    adjusted_at = Column(
        DateTime(timezone=True),
        nullable=True,
        comment="When adjustments were made"
    )
    requires_review = Column(
        sa.Boolean,
        nullable=False,
        default=False,
        comment="Flag indicating transaction needs admin review"
    )

    # Rejection tracking
    rejection_reason = Column(
        Text,
        nullable=True,
        comment="Reason for rejection"
    )
    rejected_at = Column(
        DateTime(timezone=True),
        nullable=True,
        comment="When transaction was rejected"
    )
    rejected_by_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        comment="Admin who rejected the transaction"
    )

    # Relationships
    upgrade_request = relationship("UpgradeRequest", back_populates="transaction")
    payment_method = relationship("PaymentMethod")
    coupon = relationship("Coupon", foreign_keys=[coupon_id])
    adjusted_by = relationship("User", foreign_keys=[adjusted_by_id])
    rejected_by = relationship("User", foreign_keys=[rejected_by_id])

    def __repr__(self):
        return f"<BillingTransaction {self.transaction_number} ({self.status})>"

    @staticmethod
    def generate_transaction_number() -> str:
        """Generate unique transaction number"""
        date_part = datetime.now(timezone.utc).strftime("%Y%m%d")
        unique_part = uuid.uuid4().hex[:6].upper()
        return f"INV-{date_part}-{unique_part}"

    @property
    def is_pending(self) -> bool:
        return self.status == TransactionStatus.PENDING

    @property
    def is_paid(self) -> bool:
        return self.status == TransactionStatus.PAID

    @property
    def is_cancelled(self) -> bool:
        return self.status == TransactionStatus.CANCELLED

    def mark_as_paid(self) -> None:
        """Mark transaction as paid"""
        self.status = TransactionStatus.PAID
        self.paid_at = datetime.now(timezone.utc)

    def mark_as_cancelled(self) -> None:
        """Mark transaction as cancelled"""
        self.status = TransactionStatus.CANCELLED
        self.cancelled_at = datetime.now(timezone.utc)

    def mark_as_rejected(self, rejected_by_id: UUID = None, reason: str = None) -> None:
        """Mark transaction as rejected"""
        self.status = TransactionStatus.CANCELLED
        self.rejected_at = datetime.now(timezone.utc)
        self.rejected_by_id = rejected_by_id
        self.rejection_reason = reason
        self.cancelled_at = datetime.now(timezone.utc)

    @property
    def is_refunded(self) -> bool:
        return self.status == TransactionStatus.REFUNDED

    @property
    def has_discount(self) -> bool:
        return self.discount_amount > 0 or self.coupon_id is not None

    @property
    def has_bonus(self) -> bool:
        return self.bonus_days > 0

    @property
    def net_amount(self) -> int:
        """Calculate net amount after discounts"""
        return max(0, self.amount - self.discount_amount)

    @property
    def can_be_reviewed(self) -> bool:
        """Check if transaction can be reviewed (approved/rejected)"""
        if self.status != TransactionStatus.PENDING:
            return False
        # If linked to upgrade request, check if it has payment proof
        if self.upgrade_request:
            return self.upgrade_request.status == "payment_uploaded"
        return True

    @property
    def is_standalone(self) -> bool:
        """Check if this is a standalone transaction (no upgrade request)"""
        return self.upgrade_request_id is None
