"""Add audit tracking, tenant scoping base, and tenant code

Revision ID: 73458efe5641
Revises: b7f2a1c3d4e5
Create Date: 2026-01-29 17:05:35.088225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73458efe5641'
down_revision: Union[str, Sequence[str], None] = 'b7f2a1c3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('created_by_id', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('updated_by_id', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('deleted_by_id', sa.UUID(), nullable=True))
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.UUID(),
               comment='ID of the user who performed the action (null for system actions)',
               existing_nullable=True)
    op.alter_column('audit_logs', 'tenant_id',
               existing_type=sa.UUID(),
               comment='ID of the tenant context where action occurred',
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=100),
               comment="Action performed (e.g., 'login', 'user.create', 'tenant.update')",
               existing_nullable=False)
    op.alter_column('audit_logs', 'resource',
               existing_type=sa.VARCHAR(length=100),
               comment="Resource type affected (e.g., 'user', 'tenant', 'branch', 'settings')",
               existing_nullable=False)
    op.alter_column('audit_logs', 'resource_id',
               existing_type=sa.UUID(),
               comment='ID of the specific resource affected',
               existing_nullable=True)
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Additional action details (before/after values, error info, etc.)',
               existing_nullable=True)
    op.alter_column('audit_logs', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment="Action outcome: 'success', 'failure', 'error'",
               existing_nullable=False,
               existing_server_default=sa.text("'success'::character varying"))
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment='Client IP address',
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.TEXT(),
               comment='Client user agent string',
               existing_nullable=True)
    op.alter_column('audit_logs', 'request_id',
               existing_type=sa.VARCHAR(length=36),
               comment='Request ID for correlation with application logs',
               existing_nullable=True)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.add_column('branches', sa.Column('created_by_id', sa.UUID(), nullable=True))
    op.add_column('branches', sa.Column('updated_by_id', sa.UUID(), nullable=True))
    op.add_column('branches', sa.Column('deleted_by_id', sa.UUID(), nullable=True))
    op.add_column('tenants', sa.Column('code', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('created_by_id', sa.UUID(), nullable=True))
    op.add_column('tenants', sa.Column('updated_by_id', sa.UUID(), nullable=True))
    op.add_column('tenants', sa.Column('deleted_by_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_tenants_code'), 'tenants', ['code'], unique=True)
    op.add_column('users', sa.Column('created_by_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('updated_by_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('deleted_by_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_by_id')
    op.drop_column('users', 'updated_by_id')
    op.drop_column('users', 'created_by_id')
    op.drop_index(op.f('ix_tenants_code'), table_name='tenants')
    op.drop_column('tenants', 'deleted_by_id')
    op.drop_column('tenants', 'updated_by_id')
    op.drop_column('tenants', 'created_by_id')
    op.drop_column('tenants', 'code')
    op.drop_column('branches', 'deleted_by_id')
    op.drop_column('branches', 'updated_by_id')
    op.drop_column('branches', 'created_by_id')
    op.alter_column('audit_logs', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'request_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Request ID for correlation with application logs',
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Client user agent string',
               existing_nullable=True)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment=None,
               existing_comment='Client IP address',
               existing_nullable=True)
    op.alter_column('audit_logs', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment="Action outcome: 'success', 'failure', 'error'",
               existing_nullable=False,
               existing_server_default=sa.text("'success'::character varying"))
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Additional action details (before/after values, error info, etc.)',
               existing_nullable=True)
    op.alter_column('audit_logs', 'resource_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID of the specific resource affected',
               existing_nullable=True)
    op.alter_column('audit_logs', 'resource',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Resource type affected (e.g., 'user', 'tenant', 'branch', 'settings')",
               existing_nullable=False)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Action performed (e.g., 'login', 'user.create', 'tenant.update')",
               existing_nullable=False)
    op.alter_column('audit_logs', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID of the tenant context where action occurred',
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID of the user who performed the action (null for system actions)',
               existing_nullable=True)
    op.drop_column('audit_logs', 'deleted_by_id')
    op.drop_column('audit_logs', 'updated_by_id')
    op.drop_column('audit_logs', 'created_by_id')
    # ### end Alembic commands ###
