"""Add proration billing fields

Revision ID: h3i5j6k7l8m9
Revises: g2h4i5j6k7l8
Create Date: 2026-02-13 10:00:00.000000

Adds proration support fields to:
- tenants: subscription_started_at, billing_period, credit_balance, scheduled_tier_code, scheduled_tier_effective_at
- upgrade_requests: request_type, effective_date, proration_credit, proration_charge, days_remaining, original_amount
- billing_transactions: transaction_type, credit_applied, credit_generated, original_amount, proration_details, period_start, period_end
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'h3i5j6k7l8m9'
down_revision: Union[str, Sequence[str], None] = 'g2h4i5j6k7l8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add proration billing fields."""

    # =========================================================================
    # TENANT TABLE - Add subscription tracking fields
    # =========================================================================
    op.add_column('tenants', sa.Column(
        'subscription_started_at',
        sa.DateTime(timezone=True),
        nullable=True,
        comment='When current subscription period started'
    ))
    op.add_column('tenants', sa.Column(
        'billing_period',
        sa.String(20),
        nullable=True,
        server_default="'monthly'",
        comment='Billing period: monthly or yearly'
    ))
    op.add_column('tenants', sa.Column(
        'credit_balance',
        sa.Integer(),
        nullable=False,
        server_default='0',
        comment='Credit balance in smallest currency unit'
    ))
    op.add_column('tenants', sa.Column(
        'scheduled_tier_code',
        sa.String(50),
        nullable=True,
        comment='Tier code scheduled for next billing period'
    ))
    op.add_column('tenants', sa.Column(
        'scheduled_tier_effective_at',
        sa.DateTime(timezone=True),
        nullable=True,
        comment='When scheduled tier change takes effect'
    ))

    # =========================================================================
    # UPGRADE_REQUESTS TABLE - Add proration fields
    # =========================================================================
    op.add_column('upgrade_requests', sa.Column(
        'request_type',
        sa.String(20),
        nullable=False,
        server_default="'upgrade'",
        comment='Request type: upgrade or downgrade'
    ))
    op.add_column('upgrade_requests', sa.Column(
        'effective_date',
        sa.DateTime(timezone=True),
        nullable=True,
        comment='When tier change takes effect (immediate for upgrade, end of period for downgrade)'
    ))
    op.add_column('upgrade_requests', sa.Column(
        'proration_credit',
        sa.Integer(),
        nullable=False,
        server_default='0',
        comment='Credit from unused days of current tier'
    ))
    op.add_column('upgrade_requests', sa.Column(
        'proration_charge',
        sa.Integer(),
        nullable=False,
        server_default='0',
        comment='Charge for remaining days at new tier'
    ))
    op.add_column('upgrade_requests', sa.Column(
        'days_remaining',
        sa.Integer(),
        nullable=False,
        server_default='0',
        comment='Days remaining in billing period at request time'
    ))
    op.add_column('upgrade_requests', sa.Column(
        'original_amount',
        sa.Integer(),
        nullable=False,
        server_default='0',
        comment='Full tier price before proration'
    ))

    # Index for filtering by request type
    op.create_index(
        'ix_upgrade_requests_request_type',
        'upgrade_requests',
        ['request_type']
    )

    # =========================================================================
    # BILLING_TRANSACTIONS TABLE - Add proration details
    # =========================================================================
    op.add_column('billing_transactions', sa.Column(
        'transaction_type',
        sa.String(30),
        nullable=False,
        server_default="'subscription'",
        comment='Transaction type: subscription, upgrade, downgrade, renewal, credit'
    ))
    op.add_column('billing_transactions', sa.Column(
        'credit_applied',
        sa.Integer(),
        nullable=False,
        server_default='0',
        comment='Credits used in this transaction'
    ))
    op.add_column('billing_transactions', sa.Column(
        'credit_generated',
        sa.Integer(),
        nullable=False,
        server_default='0',
        comment='Credits generated by this transaction'
    ))
    op.add_column('billing_transactions', sa.Column(
        'original_amount',
        sa.Integer(),
        nullable=False,
        server_default='0',
        comment='Amount before credits applied'
    ))
    op.add_column('billing_transactions', sa.Column(
        'proration_details',
        sa.JSON(),
        nullable=True,
        comment='JSON with proration calculation breakdown'
    ))
    op.add_column('billing_transactions', sa.Column(
        'period_start',
        sa.DateTime(timezone=True),
        nullable=True,
        comment='Billing period start date'
    ))
    op.add_column('billing_transactions', sa.Column(
        'period_end',
        sa.DateTime(timezone=True),
        nullable=True,
        comment='Billing period end date'
    ))

    # Index for transaction type queries
    op.create_index(
        'ix_billing_transactions_transaction_type',
        'billing_transactions',
        ['transaction_type']
    )
    op.create_index(
        'ix_billing_transactions_period_dates',
        'billing_transactions',
        ['period_start', 'period_end']
    )


def downgrade() -> None:
    """Remove proration billing fields."""

    # =========================================================================
    # BILLING_TRANSACTIONS TABLE
    # =========================================================================
    op.drop_index('ix_billing_transactions_period_dates', table_name='billing_transactions')
    op.drop_index('ix_billing_transactions_transaction_type', table_name='billing_transactions')
    op.drop_column('billing_transactions', 'period_end')
    op.drop_column('billing_transactions', 'period_start')
    op.drop_column('billing_transactions', 'proration_details')
    op.drop_column('billing_transactions', 'original_amount')
    op.drop_column('billing_transactions', 'credit_generated')
    op.drop_column('billing_transactions', 'credit_applied')
    op.drop_column('billing_transactions', 'transaction_type')

    # =========================================================================
    # UPGRADE_REQUESTS TABLE
    # =========================================================================
    op.drop_index('ix_upgrade_requests_request_type', table_name='upgrade_requests')
    op.drop_column('upgrade_requests', 'original_amount')
    op.drop_column('upgrade_requests', 'days_remaining')
    op.drop_column('upgrade_requests', 'proration_charge')
    op.drop_column('upgrade_requests', 'proration_credit')
    op.drop_column('upgrade_requests', 'effective_date')
    op.drop_column('upgrade_requests', 'request_type')

    # =========================================================================
    # TENANT TABLE
    # =========================================================================
    op.drop_column('tenants', 'scheduled_tier_effective_at')
    op.drop_column('tenants', 'scheduled_tier_code')
    op.drop_column('tenants', 'credit_balance')
    op.drop_column('tenants', 'billing_period')
    op.drop_column('tenants', 'subscription_started_at')
